// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: credit_request.sql

package models

import (
	"context"
	"database/sql"
)

const createCreditRequest = `-- name: CreateCreditRequest :one
INSERT INTO credit_request(
  user_id,program,member_id,transaction_time,
  amount,transaction_status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING reference_number, user_id, program, member_id, transaction_time, amount, transaction_status
`

type CreateCreditRequestParams struct {
	UserID            int32                 `json:"user_id"`
	Program           int32                 `json:"program"`
	MemberID          string                `json:"member_id"`
	TransactionTime   sql.NullTime          `json:"transaction_time"`
	Amount            float64               `json:"amount"`
	TransactionStatus TransactionStatusEnum `json:"transaction_status"`
}

func (q *Queries) CreateCreditRequest(ctx context.Context, arg CreateCreditRequestParams) (CreditRequest, error) {
	row := q.db.QueryRowContext(ctx, createCreditRequest,
		arg.UserID,
		arg.Program,
		arg.MemberID,
		arg.TransactionTime,
		arg.Amount,
		arg.TransactionStatus,
	)
	var i CreditRequest
	err := row.Scan(
		&i.ReferenceNumber,
		&i.UserID,
		&i.Program,
		&i.MemberID,
		&i.TransactionTime,
		&i.Amount,
		&i.TransactionStatus,
	)
	return i, err
}

const deleteCreditRequest = `-- name: DeleteCreditRequest :exec
DELETE FROM credit_request
WHERE reference_number = $1
`

func (q *Queries) DeleteCreditRequest(ctx context.Context, referenceNumber int64) error {
	_, err := q.db.ExecContext(ctx, deleteCreditRequest, referenceNumber)
	return err
}

const getCreditRequestByID = `-- name: GetCreditRequestByID :one
SELECT reference_number, user_id, program, member_id, transaction_time, amount, transaction_status FROM credit_request
WHERE reference_number = $1 LIMIT 1
`

func (q *Queries) GetCreditRequestByID(ctx context.Context, referenceNumber int64) (CreditRequest, error) {
	row := q.db.QueryRowContext(ctx, getCreditRequestByID, referenceNumber)
	var i CreditRequest
	err := row.Scan(
		&i.ReferenceNumber,
		&i.UserID,
		&i.Program,
		&i.MemberID,
		&i.TransactionTime,
		&i.Amount,
		&i.TransactionStatus,
	)
	return i, err
}

const getCreditRequestByProg = `-- name: GetCreditRequestByProg :many
SELECT reference_number, user_id, program, member_id, transaction_time, amount, transaction_status FROM credit_request
WHERE program = $1
`

func (q *Queries) GetCreditRequestByProg(ctx context.Context, program int32) ([]CreditRequest, error) {
	rows, err := q.db.QueryContext(ctx, getCreditRequestByProg, program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditRequest
	for rows.Next() {
		var i CreditRequest
		if err := rows.Scan(
			&i.ReferenceNumber,
			&i.UserID,
			&i.Program,
			&i.MemberID,
			&i.TransactionTime,
			&i.Amount,
			&i.TransactionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditRequestByUser = `-- name: GetCreditRequestByUser :many
SELECT reference_number, user_id, program, member_id, transaction_time, amount, transaction_status FROM credit_request
WHERE user_id = $1
`

func (q *Queries) GetCreditRequestByUser(ctx context.Context, userID int32) ([]CreditRequest, error) {
	rows, err := q.db.QueryContext(ctx, getCreditRequestByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditRequest
	for rows.Next() {
		var i CreditRequest
		if err := rows.Scan(
			&i.ReferenceNumber,
			&i.UserID,
			&i.Program,
			&i.MemberID,
			&i.TransactionTime,
			&i.Amount,
			&i.TransactionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditRequest = `-- name: ListCreditRequest :many
SELECT reference_number, user_id, program, member_id, transaction_time, amount, transaction_status FROM credit_request
ORDER BY program
`

func (q *Queries) ListCreditRequest(ctx context.Context) ([]CreditRequest, error) {
	rows, err := q.db.QueryContext(ctx, listCreditRequest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditRequest
	for rows.Next() {
		var i CreditRequest
		if err := rows.Scan(
			&i.ReferenceNumber,
			&i.UserID,
			&i.Program,
			&i.MemberID,
			&i.TransactionTime,
			&i.Amount,
			&i.TransactionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditRequest = `-- name: UpdateCreditRequest :exec
UPDATE credit_request 
SET user_id = COALESCE($1,user_id),
program = COALESCE($2,program),
member_id = COALESCE($3,member_id),
transaction_time = COALESCE($4,transaction_time),
amount = COALESCE($5,amount),
transaction_status = COALESCE($6,transaction_status)
WHERE reference_number = $7
`

type UpdateCreditRequestParams struct {
	UserID            int32                 `json:"user_id"`
	Program           int32                 `json:"program"`
	MemberID          string                `json:"member_id"`
	TransactionTime   sql.NullTime          `json:"transaction_time"`
	Amount            float64               `json:"amount"`
	TransactionStatus TransactionStatusEnum `json:"transaction_status"`
	ReferenceNumber   int64                 `json:"reference_number"`
}

func (q *Queries) UpdateCreditRequest(ctx context.Context, arg UpdateCreditRequestParams) error {
	_, err := q.db.ExecContext(ctx, updateCreditRequest,
		arg.UserID,
		arg.Program,
		arg.MemberID,
		arg.TransactionTime,
		arg.Amount,
		arg.TransactionStatus,
		arg.ReferenceNumber,
	)
	return err
}
